---
- include_tasks: packages.yml
#- include_tasks:

- name: tmpfiles config
  copy:
    dest: /lib/tmpfiles.d/mongodb.conf
    content: "d /var/run/mongodb 0755 mongod mongod"

- name: tmpfiles create
  command: systemd-tmpfiles --create mongodb.conf

- name: mongo keyfile
  shell: "openssl rand -base64 756 > /tmp/mongo-keyfile"
    #creates: /tmp/mongo-keyfile
  delegate_to: localhost
  run_once: true

- name: check if keyfile exists
  stat:
    path: /var/lib/mongo/mongo-keyfile
  register: mongo_keyfile

- name: copy mongo keyfile
  copy:
    src: /tmp/mongo-keyfile
    dest: /var/lib/mongo
    owner: mongod
    group: mongod
    mode: 0400
  when: mongo_keyfile.stat.exists != true
