---
- name: Add mongodb repo
  yum_repository:
    name: "mongodb-org-4.2"
    description: MongoDB Repository
    file: mongodb
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: install epel repo
  package:
    name: epel-release

- name: install mongodb
  package:
    name:
      - mongodb-org
      - python2-pip

- name: install pymongo pip
  pip:
    name: pymongo
