---
- hosts: all
  roles:
  - role: mongodb

- hosts: footloose_config
  roles:
    - role: mongodb-config

- hosts: footloose_route
  roles:
    - role: mongodb-route

- hosts: footloose_shard
  roles:
    - role: mongodb-shard
