---
# start mongod to enable authentification
- name: start mongod
  service:
    name: mongod
    enabled: yes
    state: started

# try to create admin user,
# if it fails authentification is already enabled
- name: create admin user
  mongodb_user:
    name: mongo-admin
    password: "{{admin_password}}"
    database: admin
    roles: 'root'
  tags:
    - admin
  ignore_errors: true
  #when: inventory_hostname == groups[group_names[0]][0]

- name: create config
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify:
    - restart mongod

- name: flush handlers
  meta: flush_handlers

- name: create replica set
  mongodb_replicaset:
    login_host: "{{inventory_hostname}}"
    login_port: 27019
    login_user: mongo-admin
    login_database: admin
    login_password: "{{admin_password}}"
    replica_set: configReplSet
    members: "{{ansible_play_hosts | map('regex_replace', '$', ':27019') | list }}"
  when: inventory_hostname == groups[group_names[0]][0]
  #run_once: true
  tags: replica
