---
- name: create mongos config
  template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf
    owner: mongod
    group: mongod

- name: create mongos systemd unit file
  template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
